charts/buildbuddy/Chart.yaml
charts/buildbuddy/requirements.yaml
charts/buildbuddy/templates/ingress.yaml
charts/buildbuddy/values.yaml

Hi there 👋🏻 I _think_ this may be a copy/paste mistake in the `requirements.yaml`, but if it's intentionally set to `ingress.enabled`, apologies for taking your bandwidth!
Also parameterises `ingress.class` to allow the easy use of different ingress types

Only include certmanager if it's enabled & parameterise ingress class

---

charts/buildbuddy/templates/deployment.yaml

Hi again 👋🏻 we were hoping to have some affinities and nodeSelectors to our BuildBuddy instance, and were hoping you'd be happy to extend the chart to allow for that.
This felt like a nicer approach than adding each thing individually, but if you'd prefer a PR in that direction happy to do either approach!
Example usage:
```yaml
extraPodSpec:
nodeSelector:
node.kubernetes.io/instance-type: c5.4xlarge
tolerations:
- key: "target"
operator: "Equal"
value: "abcdef"
effect: "NoSchedule"
```

Add extraPodSpec for extending pod definitions

---

charts/buildbuddy-executor/Chart.yaml
charts/buildbuddy-executor/templates/_helpers.tpl

The executor doesn't use Ingress, this just keeps the helpers in line with the other versions from #9 and #10

Update the executor charts

---

charts/buildbuddy-redis/Chart.yaml
charts/buildbuddy-redis/templates/_helpers.tpl

Redis doesn't use Ingress, this just keeps the helpers in line with the other versions from #9 and #10

Update the redis helpers

---

charts/buildbuddy-redis/templates/service.yaml

I found that selector is redefined in the buildbuddy-redis charts

Fix the redefined selector in buildbuddy-redis

---

charts/buildbuddy/Chart.yaml
charts/buildbuddy/templates/ingress.yaml

This is just a quick fix for the apiVersion in the `ingress.yaml` following this recent change #10 to the open-source version.
Tried upgrading BB from 0.32 to the latest, and noticed since the apiVersion ref was taken out of the named template, upgrading would complain with `error calling include: template: no template "buildbuddy.ingress.apiVersion"`

Update open-source ingress ApiVersion

---

charts/buildbuddy-enterprise/templates/deployment.yaml
charts/buildbuddy-enterprise/templates/service.yaml
charts/buildbuddy-executor/templates/deployment.yaml
charts/buildbuddy-redis/templates/deployment.yaml
charts/buildbuddy-redis/templates/service.yaml
charts/buildbuddy/templates/deployment.yaml
charts/buildbuddy/templates/service.yaml

This selector isn't really necessary, and causes issues when releasing with Spinnaker as Spinnaker overwrites the label:
> Deploy failed: The Deployment "buildbuddy-executor" is invalid: spec.template.metadata.labels: Invalid value: map[string]string{"app.kubernetes.io/instance":"buildbuddy", "app.kubernetes.io/managed-by":"spinnaker", "app.kubernetes.io/name":"executor", "helm.sh/chart":"executor-0.0.105", "team":"infrastructure"}: selector does not match template labels

Remove app.kubernetes.io/managed-by selectors

---

charts/buildbuddy-enterprise/Chart.yaml
charts/buildbuddy-enterprise/templates/ingress.yaml
charts/buildbuddy-enterprise/values.yaml

Ensure that user could customize the ingress.class to other values such as "alb" or "nginx". The default "nginx" value is not changed.

enterprise: make ingress.class configurable

---

charts/buildbuddy-enterprise/Chart.yaml
charts/buildbuddy-enterprise/templates/alb.yaml
charts/buildbuddy-enterprise/templates/ingress.yaml
charts/buildbuddy-enterprise/values.yaml

Add basic support for using AWS's LoadBalancer as Ingress on EKS.
This was split from https://github.com/buildbuddy-io/buildbuddy-helm/pull/40
Add support for ALB Ingress using AWS LoadBalancer Controller(1) on EKS.
(1): https://github.com/kubernetes-sigs/aws-load-balancer-controller/
---
Version bump: Patch

Ingress: support ALB

---

charts/buildbuddy-executor/Chart.yaml
charts/buildbuddy-executor/templates/deployment.yaml

When podman is enabled, we need to mount some dedicated emptyDir volume into the Executor container so that podman could download and store container images onto these paths.

executor: add missing mounts when podman is enabled

---

charts/buildbuddy-executor/Chart.yaml
charts/buildbuddy-executor/templates/deployment.yaml

When podman isolation type is used, our executor would run child
runner containers inside the executor container(parent) using
'podman'.
This requires the executor container to be executed with privileged.

executor: require privileged with podman

---

charts/buildbuddy-executor/templates/deployment.yaml

The extraInitContainers value was not utilized in the template. This PR makes it so that the extraInitContainers value works as expected.

[charts/buildbuddy-executor] Utilize extraInitContainers value

---

charts/buildbuddy-executor/templates/deployment.yaml

When the executor config has `docker_socket` set to `""`, the chart still mounted the docker socket to the executor pod. We would like to avoid this, so that we can run a bare executor without needing `/var/run/docker.sock` to exist on the host.

[charts/buildbuddy-executor] Avoid mounting docker socket when set to empty in config

---

charts/buildbuddy-executor/templates/deployment.yaml

This PR prevents adding `SYS_MEMORY_BYTES` and `SYS_MILLICPUS` environment variables to the executor pod, if those values are set in the executor config. As documented in the executor config [here](https://www.buildbuddy.io/docs/config-all-options#buildbuddy-executor), these values should only be set either by the environment variables or the config, but not both. This PR reflects those requirements in the helm chart.

[charts/buildbuddy-executor] Only set SYS_* environment variables if they are not in the config

---

charts/buildbuddy-executor/Chart.yaml
charts/buildbuddy-executor/templates/deployment.yaml

I only tested my change to add `customExecutorCommand`, with one element in the list. When there's multiple elements in the `customExecutorCommand`, it failed. 
This fixes the issue by converting the `customExecutorCommand` to yaml in the template.

Fix customExecutorCommand

---

charts/buildbuddy-executor/Chart.yaml
charts/buildbuddy-executor/templates/deployment.yaml

Removing containerd volumes as it communicates wrong information.
Podman does not require containerd to be mounted to Node's hostPath to
work. Mounting containerd paths (1) does help with debugging podman
during development however.
Move the required executor-data mount to the top of the volumes list to
improve readability.
(1): https://github.com/containerd/containerd/blob/v1.7.2/docs/ops.md#base-configuration

executor: remove unused podman volumes

---

charts/buildbuddy-enterprise/templates/alb.yaml
charts/buildbuddy-executor/Chart.yaml

Let's not gate the host configuration behind a test-only config flag.

enterprise/alb: include hostname in spec rule

---

charts/buildbuddy-executor/Chart.yaml
charts/buildbuddy-executor/templates/deployment.yaml

This is a follow up from
https://github.com/buildbuddy-io/buildbuddy/pull/4326.
Make use of the new variable.
Set `$HOME=/buildbuddy` to retain the `.config/buildbuddy/host_id` between accidental container restarts.

executor: pass pod's UID to executor

---

charts/buildbuddy-executor/Chart.yaml
charts/buildbuddy-executor/templates/deployment.yaml

When podman is enabled but there isn't a security context available in
values.yaml config, the 'privileged' setting, required for running
nested podman container within a pod, is not properly rendered.
Provide an additional `else if` clause for that scenario.
Closes https://github.com/buildbuddy-io/buildbuddy-internal/issues/2550

executor: ensure that securityContext is set when podman is used

---

charts/buildbuddy-executor/templates/deployment.yaml

In #63, we set a custom $HOME env variable pointing to /buildbuddy,
which is an emptyDir volumeMount, so that configs stored in
`os.UserConfigDir() + "/buildbuddy"` is persisted. (1) (2)
However, as #65 pointed out, overriding $HOME will cause container tools
such as docker, podman, to look up configs and credential helpers in the
wrong directory.
Unset the custom $HOME. Create a custom emptyDir volume mount for the
buildbuddy user config dir.
Closes #65.
(1): https://github.com/buildbuddy-io/buildbuddy/blob/c41d920e53326e75b7bb5c44d2b704ecac0e0ff9/server/util/uuid/uuid.go#L74-L79
(2): https://pkg.go.dev/os#UserConfigDir

Avoid setting custom $HOME

---

charts/buildbuddy-enterprise/Chart.yaml
charts/buildbuddy-enterprise/templates/alb.yaml
charts/buildbuddy/Chart.yaml
charts/buildbuddy/templates/ingress.yaml

The annotation `kubernetes.io/ingress.class` has been deprecated since
Kubernetes 1.18 in favor of spec.ingressClassName.
However, some controllers, such as GKE Ingress controller, are still
mandate usage of the deprecated annotation. (1)
Remove the annotation specifically for ALB use case for now.
Future improvements could potentially make this annotation GKE specific
depending on users' reports.
(1): https://cloud.google.com/kubernetes-engine/docs/concepts/ingress#deprecated_annotation
Closes #67

ingress: stop using ingress.class annotation for ALB

---

charts/buildbuddy-executor/Chart.yaml
charts/buildbuddy-executor/templates/autoscaler.yaml
charts/buildbuddy-executor/values.yaml

Some executor deployments will consume and retain memory on the host,
which make CPU/Memory based scaling inaccurate.
RBE queue length is a much better metrics to determine when
you should scale up/down your executor deployment.

executor: remove autoscaling based on CPU/Memory

---

charts/buildbuddy-executor/Chart.yaml
charts/buildbuddy-executor/templates/deployment.yaml
charts/buildbuddy-executor/values.yaml

Provide a configuration that would let user slow down the replacement of
pods during a RollingUpdate. This should give newer pods time to warm up
and reach the desired action execution speed, before shutting down the
older pods.

executor: add support for minReadySeconds

---

charts/buildbuddy-executor/Chart.yaml
charts/buildbuddy-executor/templates/deployment.yaml

This was wrongly set in Pod Template spect instead of Deployment spec.
Thanks to @amartani for the report

executor: move minReadySeconds to deployment spec      

---

charts/buildbuddy-executor/Chart.yaml
charts/buildbuddy-executor/templates/deployment.yaml

Explicitly setting `replicas` will cause Kubernetes to always set the number of replicas to the specified value, even when autoscaling is in use. The impact is that, during any update, the number of replicas will go back to the configured value and will have to rely on autoscaling to bring it back to the original value. Excluding `replicas` when autoscaling is enabled allows it to maintain the value from autoscaling during upgrades.
See https://github.com/kubernetes/kubernetes/issues/25238

executor: Do not set replicas when autoscaling is enabled

---

charts/buildbuddy-redis/Chart.yaml
charts/buildbuddy-redis/templates/deployment.yaml
charts/buildbuddy-redis/values.yaml

Follow-up for PR #71 - change did not include `buildbuddy-redis` Chart. Also while at it, allowing specifying `nodeSelector`.

buildbuddy-redis: allow specifying tolerations and nodeSelector

---

charts/buildbuddy-enterprise/Chart.yaml
charts/buildbuddy-enterprise/templates/grafana.yaml
charts/buildbuddy-enterprise/templates/ingress.yaml

This annotation was marked as deprecated in 2020
https://kubernetes.io/blog/2020/04/02/improvements-to-the-ingress-api-in-kubernetes-1.18/#deprecating-the-ingress-class-annotation.
Replace it with `spec.ingressClassName`

enterprise: replace deprecated ingress annotations

---

charts/buildbuddy/Chart.yaml
charts/buildbuddy/templates/service.yaml

This allows ingresses other than nginx know that the service should receive HTTP/2 requests without needing for negotiation.
For example, the ngrok Ingress Controller uses it: https://github.com/ngrok/kubernetes-ingress-controller

Add appProtocol for gRPC ports

---

charts/buildbuddy-executor/Chart.yaml
charts/buildbuddy-executor/templates/deployment.yaml

Podman has 2 default storage path:
- Graph Root: /var/lib/containers/storage
- Run Root: /run/containers/storage
As of recent version of Podman, the default SQLite database that is used
to keep track of container states are written to Graph Root.
However, when the transient store option is enabled, podman will write
the database to Run Root path instead. (1)
Provide a dedicated mountPath for Run Root using emptyDir.
Users are advised to make sure that the underlying filesystem / disk
that is serving this Run Root to be performance enough so that the
SQLite database is not throttle podman container operations.
Avoiding Network Storage solution should suffice.
(1): https://github.com/containers/podman/blob/6487940534c1065d6c7753e3b6dfbe253666537d/libpod/sqlite_state.go#L61-L66

executor: add additional volume mount for run root

---

charts/buildbuddy-enterprise/Chart.yaml
charts/buildbuddy-enterprise/templates/deployment.yaml
charts/buildbuddy-enterprise/values.yaml
charts/buildbuddy/Chart.yaml
charts/buildbuddy/templates/deployment.yaml
charts/buildbuddy/values.yaml

In the future, we want to add support for other databases to this helm
chart, such as ClickHouse for OLAP workloads. Each of these new
databases will require their own init containers to check if the main
port is available.
Instead of using multiple container images for multiple tools, let's
simplify the setup using netcat `nc` inside `busybox` image.

mysql: change init container to busybox and nc

---

charts/buildbuddy-executor/templates/deployment.yaml
charts/buildbuddy-executor/values.yaml

On some platforms such as AWS's EKS, user might want to move their
entire executor-data volume onto a RAID-0 over NVMe instance store disks
as described in (1).
Currently, this could be achieved with a combination of `extraVolumes`,
`extraVolumeMounts`, and then set `config.executor.root_directory`
and `config.executor.local_cache_directory` to the desired path(s).
However, such a setup could be unweildy and harder to maintain.
Provide a config that would let users change `executor-data`,
which corresponds to the `/buildbuddy` dir inside our container, from
`emptyDir` to `hostPath`.
(1): https://aws.amazon.com/blogs/containers/eks-persistent-volumes-for-instance-store/

executor: allow custom executor-data location

---

charts/buildbuddy-enterprise/Chart.yaml
charts/buildbuddy-enterprise/templates/alb.yaml
charts/buildbuddy-enterprise/templates/ingress.yaml

We no longer need to support `user@my-buildbuddy.io` host name now that
Bazel comes with `--remote_header=` flag.

enterprise: remove at-grpc ingress

---

charts/buildbuddy-executor/Chart.yaml
charts/buildbuddy-executor/templates/deployment.yaml
charts/buildbuddy-executor/values.yaml

In some Kubernetes setup, emptyDir volume could point to slower
network storage on the Node.
Provide configs to set podman volumes to use host paths instead of
emptyDir. Users could use these configs to setup these volumes on
a faster storage medium on the Nodes.

executor: add host path config for podman volumes

---

charts/buildbuddy/templates/deployment.yaml

This was accidentally added in
https://github.com/buildbuddy-io/buildbuddy-helm/pull/98.
Reported-by: @blackliner

buildbuddy: fix wrong init-mysql command

---

charts/buildbuddy-executor/Chart.yaml
charts/buildbuddy-executor/templates/poddisruptionbudget.yaml
charts/buildbuddy-executor/values.yaml

adds an optional PodDisruptionBudget object to the executor chart. this is useful for enforcing a baseline level of capacity during node replacement operations.
arguably a minor version bump, but I opted for a patch given that it's still 0.0.x. happy to make it 0.1.0 if desired.

add PodDisruptionBudget to executor chart

---

charts/buildbuddy-enterprise/Chart.yaml
charts/buildbuddy-enterprise/migration-cache.values.yaml
charts/buildbuddy-enterprise/values.yaml

Switch from disk cache to pebble cache as the default cache storage
backend.
Also provide an example of how Migration Cache could be setup for future
references.

enterprise: default to Pebble cache

---

charts/buildbuddy-executor/templates/autoscaler.yaml
charts/buildbuddy-executor/values.yaml

Provide the ability to use a custom set of metrics for the autoscaler.
This enable folks who rely on a custom metric adapter, such as (1), to
use a different metric name than the default name straight from out
application.
(1): https://cloud.google.com/kubernetes-engine/docs/tutorials/autoscaling-metrics

executor: support using custom metrics with autoscaler

---

charts/buildbuddy-executor/Chart.yaml
charts/buildbuddy-executor/templates/deployment.yaml
charts/buildbuddy-executor/values.yaml

we'd like our executors running in AWS EKS to pull docker images from our private ECR registry. the pods need AWS IAM credentials to auth to the docker registry, which we can conveniently get IAM creds in EKS via [IRSA](https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html), but we need to be able to set the service account name that the pod uses.
- executor values.yaml: add `serviceAccount.name` value, default to current behaviour (use `default` SA)
- deployment.yaml: use the service account, if specified
still renders when value is not set, also does not set serviceAccountName
```
bash-5.2$ helm template . | grep serviceAccount
```
when setting the `.serviceAccount.name`, it shows up in the spec as expected
```
bash-5.2$ helm template . --set …
```

executor: Add an optional serviceAccount.name to values.yaml

---

charts/buildbuddy-enterprise/Chart.yaml
charts/buildbuddy-enterprise/templates/ingress.yaml
charts/buildbuddy-enterprise/values.yaml

In the latest version of nginx ingress, the ordering of
`nginx.ingress.kubernetes.io/configuration-snippet` could be placed
before our http-snippet and thus, cause $api_key variable to be
undefined and fail the invalidation hook.
Move the grpc_set_header calls to directly below relevant http-snippet
and make them conditional.
Fixed missing host auth-type.
Replaced obsoleted `http2_max_requests` with `keepalive_requests`.

enterprise: adjust nginx ingress config

---

charts/buildbuddy-executor/Chart.yaml
charts/buildbuddy-executor/templates/deployment.yaml
charts/buildbuddy-executor/values.yaml

"oci" isolation is our own container runtime based on crun.
It has less performance overhead compare to podman while being
compatible with existing container images.
We have been using it in our production environment for several months
now and should be matured enough for our customers to adopt it as well.
Similar to podman isolation, "oci" isolation runs action containers
inside the Executor container of the kubernetes pod. This means that the
outer Executor container requires priviledged permission to perform
setup needed for the action containers to run.

executor: switch default isolation from podman to oci

---

charts/buildbuddy-enterprise/Chart.yaml
charts/buildbuddy-enterprise/values.yaml

`if` directive is not allowed inside the main http block.
Revert to the previous logic where we set these headers
unconditionally.

enterprise/ingress: remove condition around grpc_set_header

---

charts/buildbuddy-executor/Chart.yaml
charts/buildbuddy-executor/templates/deployment.yaml
charts/buildbuddy-executor/values.yaml

Users may want to customize their liveness/readiness probe to precisely
control how the pod is startup and health check.
https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#configure-probes

executor: allow extra configuration for probes

---

charts/buildbuddy-enterprise/Chart.yaml
charts/buildbuddy-enterprise/templates/deployment.yaml
charts/buildbuddy-enterprise/values.yaml

Mirror the existing configuration from buildbuddy-executor helm chart.
Requested by one of our user via email.

buildbuddy-enterprise: add optional serviceAccount configuration

---

charts/buildbuddy-executor/Chart.yaml
charts/buildbuddy-executor/templates/deployment.yaml

Firecracker doesn't work unless in privileged mode.
Context: https://buildbuddy-corp.slack.com/archives/C0777L0C2UW/p1757023006056969?thread_ts=1756935242.851329&cid=C0777L0C2UW

Enable privileged security context if firecracker is enabled
